services:
  server:
    restart: always
    build:
      context: .
      # dockerfile: ./server.Dockerfile
      dockerfile: ./server/Dockerfile
    container_name: server-jbx
    environment:
      - NODE_ENV=network
      - PORT=9000
      - HOST=localhost
      - JWT_SECRET_KEY=changeme
      - TOKEN_HEADER_KEY=Authorization
      - MONGO_URI=mongodb://root:changeme@mongo-network-jbx:27017
      - LOG_LEVEL=debug
      - KAFKA_BROKERS=kafka-jbx:9092
      - BASE_URL=http://localhost:8080
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    ports:
      - 9000:9000
    depends_on:
      - mongodb
      - kafka
    volumes:
      - ./server:/app/server
      - ./packages:/app/packages
    networks:
      - cluster
    command: npm run dev:server

  proxy:
    build:
      context: ./proxy/
    ports:
      - 8080:8080
    networks:
      - cluster
    depends_on:
      - server
    volumes:
      - client-dist:/vol/client
    environment:
      - SERVER_URI=server-jbx:9000
      - WEBSOCKET_URI=websocket-jbx:9001
    attach: false

  mongodb:
    image: mongo:6.0.9
    restart: always
    container_name: mongo-network-jbx
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    command: mongod --quiet --logpath /dev/null --bind_ip_all
    networks:
      - cluster
  
  ####################################
  # Kafka Config
  ####################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-jbx
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - cluster
    attach: false

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-jbx
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-jbx:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-jbx:9092,PLAINTEXT_HOST://localhost:29092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - cluster
    attach: false
      
  kafka-api:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./kafka-api
    container_name: kafka-api-jbx
    ports:
      - 9090:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - kafka
  
  ####################################
  # Web Socket Config
  ####################################
  websocket:
    build:
      context: ./
      dockerfile: ./websocket/Dockerfile
    restart: always
    ports:
      - 9001:9001
    container_name: websocket-jbx
    volumes:
      - ./websocket:/app/websocket
      - ./packages:/app/packages
      - ./package.json:/app/package.json
    environment:
      - HOST=0.0.0.0
      - PORT=9001
      - NODE_ENV=network
      - LOG_LEVEL=debug
      - KAFKA_BROKERS=kafka-jbx:9092
      - KAFKA_GROUP_ID=websocket-jbx
      - LOG_NS=websocket
      # - BYPASS_AUTH=1
    command: npm run dev:websocket
    networks:
      - cluster

volumes:
  client-dist:
    name: client-dist
  mongo-data:

networks:
  cluster:
    name: jukebox_cluster
    driver: bridge
