apiVersion: v1
kind: ConfigMap
metadata:
  name: jukebox-server-config
  namespace: main
data:
  NODE_ENV: 'production'
  PORT: '9000'
  HOST: 'localhost'
  LOG_LEVEL: 'debug'
  BASE_URL: 'http://localhost:30080'
  PROXY_URL: 'http://proxy:8080'
  DB_HOST: 'postgres'
  DB_PORT: '5432'
  DB_USER: 'devuser'
  DB_PASS: 'devpass'
  DB_NAME: 'devdatabase'
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'

