apiVersion: apps/v1
kind: Deployment
metadata:
  name: jukebox-server
  namespace: main
spec:
  selector:
    matchLabels:
      app: jukebox-server
  replicas: 1
  template:
    metadata:
      labels:
        app: jukebox-server
    spec:
      containers:
        - name: jukebox-server-api
          image: ikehunter5/jukebox-server:latest
          envFrom:
            - configMapRef:
                name: jukebox-server-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: main
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: ikehunter5/jukebox-proxy:latest
          envFrom:
            - configMapRef:
                name: proxy-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-manager
  namespace: main
spec:
  selector:
    matchLabels:
      app: club-manager
  template:
    metadata:
      labels:
        app: club-manager
    spec:
      containers:
        - name: club-manager
          image: ikehunter5/club-manager:latest
          envFrom:
            - configMapRef:
                name: club-manager-config
